### ISSUE TITLE
TOCの実装

### ISSUE THREAD

**Issue by nao-toyo** [naoyuki29/naonotejs#16]
markdownの見出しからTOCを作成する。
サイドバーに表示し、見出しをクリックするとその項目までジャンプできるようにする。

表示：Affixの使用??

**Comment by naoyuki-u** [comment]
プラグイン使って簡単にmarkdownからTOCの元となる情報を抽出できる。
しかもご丁寧に各項目へのリンクを生成した状態で返してくれる。
せっかくなので、これをそのまま使うことにする。
プラグインについては下記参照
[ここ](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/#configuring-the-tableofcontents)

**Comment by naoyuki29** [comment]
上記PRでサイドバーにTOCを表示する機能を実装。
以下を確認

- header情報を列挙すること
- header階層に応じてTOCにリストされる階層も変わること
- 現在ブラウザに表示している項目がハイライトされること
